export const GET_CREDIT_REPORT_REQUEST = 'creditReport/GET_CREDIT_REPORT_REQUEST'
export const GET_CREDIT_REPORT_SUCCESS = 'creditReport/GET_CREDIT_REPORT_SUCCESS'
export const GET_CREDIT_REPORT_ERROR = 'creditReport/GET_CREDIT_REPORT_ERROR'
